# Generated by Django 4.0 on 2022-01-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=32)),
                ('market_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'StockInfo',
            },
        ),
    ]
